# Generated by Django 4.1 on 2022-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0002_alter_payment_mode_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="mode",
            field=models.CharField(
                choices=[("CIB", "CIB"), ("EDAHABIA", "EDAHABIA")],
                default="EDAHABIA",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "PAID"),
                    ("progress", "IN PROGRESS"),
                    ("expired", "EXPIRED"),
                    ("failed", "FAILED"),
                    ("canceled", "CANCELED"),
                ],
                default="progress",
                max_length=25,
            ),
        ),
    ]
